--créer un nouveau role admin
CREATE ROLE "admin" WITH 
SUPERUSER
CREATEDB
CREATEROLE
NOINHERIT
LOGIN
NOREPLICATION
NOBYPASSRLS
CONNECTION LIMIT -1;

ALTER ROLE admin WITH PASSWORD 'admin';
--create un nouveua schema dev
CREATE SCHEMA dev AUTHORIZATION "admin";
--grant priveleges to admin on schema dev et public
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL ON FUNCTIONS TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA dev GRANT ALL ON SEQUENCES TO "admin";
GRANT ALL ON SCHEMA public TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT TRUNCATE, TRIGGER, REFERENCES, UPDATE, DELETE, INSERT ON TABLES TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "admin";

--
CREATE ROLE web_anon NOLOGIN;

GRANT USAGE ON SCHEMA dev TO web_anon;
GRANT USAGE ON SCHEMA dev TO web_anon;